spring:
  config:
    import:
      - classpath:/yml/application-local.yml
      - classpath:/yml/application-oauth.yml
      - classpath:/yml/application-dev.yml
  profiles:
    active: dev
    include: oauth