# 각 환경마다 사용할 Datasource 값 설정
local-db:
  url: jdbc:mysql://localhost:3306/infp
  username: root
  password: 1234

dev-db:
  url: jdbc:mysql://13.125.244.210:3306/infp
  username: user
  password: password

secret:
  key: 7JWI64WV7ZWY7IS47JqU6rmA7IiY7ZmY7J6F64uI64uk

local-redis:
  host: localhost
  port: 6379

dev-redis:
  host: 13.125.244.210
  port: 6379