spring:
  config:
    import:
    - classpath:/yml/application-secret.yml
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${dev-db.url}
    username: ${dev-db.username}
    password: ${dev-db.password}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
    show-sql: true

  data:
    redis:
      host: ${dev-redis.host}
      port: ${dev-redis.port}

springdoc:
  show-login-endpoint: true

jwt:
  secret:
    key:
      access: ${secret.key.access}
      refresh: ${secret.key.refresh}

cloud:
  aws:
    region:
      static: ${aws.region.static}
    stack:
      auto: ${aws.stack.auto}
    credentials:
      accessKey: ${aws.credentials.accessKey}
      secretKey: ${aws.credentials.secretKey}
    s3:
      bucket: ${aws.s3.bucket}