name: Deploy to AWS EC2

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
# 사용할 인프라의 이름을 변수 형태로 저장
jobs:
  build-and-deploy:
    # 실행 환경 지정
    runs-on: ubuntu-latest
    # Task sequence 명시
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      # Github Actions 워크플로우가 실행되는 가상 환경내에 application-dev 설정
      - name: Generate application-secret.yml
        run: echo "${{ secrets.APPLICATION_SECRET_CONTENT }}" > ./src/main/resources/yml/application-secret.yml

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Build Docker image
        run: docker build . -t myapp:${{ github.sha }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push image to Amazon ECR
        run: |
          docker tag myapp:${{ github.sha }} ${{ secrets.AWS_ECR_REPOSITORY_URL }}:latest
          docker push ${{ secrets.AWS_ECR_REPOSITORY_URL }}:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ${{ secrets.AWS_ECR_REPOSITORY_URL }}:latest
            docker stop myapp || true
            docker rm myapp || true
            docker run -d --name myapp -p 80:8080 ${{ secrets.AWS_ECR_REPOSITORY_URL }}:latest
